package DataStructure.D_Recursion;

// find possible word which generated by 2 keys of keyped mobile

import java.util.Scanner;

public class KeypadProblem {

    private static final String[]  keyPad= {"","abc","def","ghi","jkl","mno","pqrs","tuv","wxyz"};

    public static void printKeypadSequence(String firstStr,String secondStr,String ans){
        
    }

    public static void main(String[] arr){

        Scanner sc=new Scanner(System.in);
        int firstNumber=sc.nextInt();
        int secondNumber=sc.nextInt();
        printKeypadSequence(keyPad[firstNumber],keyPad[secondNumber],"");

    }
}
